### ISSUE TITLE
installing iconv@1.0.0 fails

### ISSUE THREAD

**Issue by jeffcrouse** [mitmedialab/Junkyard-Jumbotron#3]
I realize that this is 2 years old, but FWIW:

Step: "make node-packages"
Platform: OS X 10.8.1
Node version: v0.10.7

It tries to use "node-waf", which is apparently deprecated

In fact, it seems that a few of the modules have problems with the versions specified.  I may have cause to make a fork and whip up a package.json.  Any thoughts on this?

**Comment by JeremyRubin** [comment]
Try checking my branch's version - https://github.com/JeremyRubin/Junkyard-Jumbotron . I think I fixed some stuff there. Also there is limited support for video playback, which you may find interesting.

**Comment by jeffcrouse** [comment]
thanks for the tip! I will check it out.

**Comment by kaiba22** [comment]
I try "node jjserver.js" and i have this error: 

Error: require.paths is removed. Use node_modules folders, or the NODE_PATH environment variable instead.
    at Function.Object.defineProperty.get (module.js:388:11)
    at module.exports (/home/carlos/Documents/Projects/Junkyard-Jumbotron/node_modules/log4js/lib/log4js.js:519:41)
    at Object.<anonymous> (/home/carlos/Documents/Projects/Junkyard-Jumbotron/node_modules/jjserver.js:20:31)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:902:3

any ideas ? 

thanks

**Comment by bleppie** [comment]
Sounds like you have a newer version of node.js. You need to use an older one, I'm not sure which, but hopefully it's specified somewhere in the install.

**Comment by kaiba22** [comment]
does anyone know what the correct version of nodejs to use?

**Comment by ccardoso** [comment]
Hello, I have this error when try upload a photo

ERROR: jjteste controller 1 > bad image Can't handle file uploaded to 'jjteste'
Currently we only support images and movies (no text files) in jpeg, png, ogv, and gif formats.

I try png format

**Comment by ccardoso** [comment]
bleppie I get this error wen I try upload an image of my screens: 

ERROR: newController controller 0 > Error: Command failed: /bin/sh: 1: python: not found

I have python installed and i have configure paramsLocal for path /usr/bin/python2.7

can anyone help me!!!

**Comment by rafaelbuiu** [comment]
@jefftimesten  hey man, you should change the Make file and swap the iconv version to the most updated.

**Comment by SigmazGFX** [comment]
So I know this has been set out to pasture, but is there any way to get it to work anymore?
I'm running on Ubuntu 16.04 LTS
Compiling errors and fails at every turn.
node-waf is depreciated and other parts are broken as well. 
Is anyone willing to run through and freshen this up? or at least tell me which versions of what are requires to make it work?
